syntax = "proto3";

package remote_output_service;

import "build/bazel/remote/execution/v2/remote_execution.proto";
import "google/protobuf/empty.proto";

option java_package = "com.google.devtools.build.lib.remote";
option java_outer_classname = "RemoteOutputServiceProto";
option go_package = "remoteoutputservice";

// The Remote Output Service may be used by users of the Remote
// Execution API to construct a directory on the local system that
// contains all output files of a build.
//
// Primitive implementations of this API may simply download files from
// the Content Addressable Storage (CAS) and store them at their
// designated location. Complex implementations may use a pseudo file
// system (e.g., FUSE) to support deduplication, lazy loading and
// snapshotting.
//
// Details:
// https://github.com/bazelbuild/proposals/blob/master/designs/2021-02-09-remote-output-service.md
// https://groups.google.com/g/remote-execution-apis/c/qOSWWwBLPzo
// https://groups.google.com/g/bazel-dev/c/lKzENsNd1Do
service RemoteOutputService {
  // Methods that can be invoked at any point in time.

  // Clean all data associated with a single output path, so that the
  // next invocation of StartBuild() yields an empty output path. This
  // may be implemented in a way that's faster than removing all of the
  // files from the file system manually.
  rpc Clean(CleanRequest) returns (google.protobuf.Empty);

  // Signal that a new build is about to start.
  //
  // The client uses this call to obtain a directory where outputs of
  // the build may be stored, called the output path. Based on the
  // parameters provided, the remote output service may provide an empty
  // output path, or one that has contents from a previous build of the
  // same workspace.
  //
  // In case the output path contains data from a previous build, the
  // remote output service is responsible for calling
  // ContentAddressableStorage.FindMissingBlobs() for all of the objects
  // that are stored remotely. This ensures that these objects don't
  // disappear from the Content Addressable Storage while the build is
  // running. Any files that are absent must be removed from the output
  // path and reported through InitialOutputPathContents.modified_paths.
  rpc StartBuild(StartBuildRequest) returns (StartBuildResponse);

  // Create one or more files, directories or symbolic links in the
  // output path.
  rpc BatchCreate(BatchCreateRequest) returns (google.protobuf.Empty);

  // Signal that a build has been completed.
  rpc FinalizeBuild(FinalizeBuildRequest) returns (google.protobuf.Empty);
}

message CleanRequest {
  // The output base identifier that was provided to
  // StartBuildRequest.workspace_id whose data needs to be removed.
  string workspace_id = 1;
}

message StartBuildRequest {
  // A client-chosen value that uniquely identifies this build. This
  // value must be provided to most other methods to ensure that
  // operations are targeted against the right output path.
  string build_id = 1;

  // A client-chosen value that uniquely identifies the workspace for
  // which the build is being started.  This value must be set to ensure
  // that the remote output service is capable of managing builds for
  // distinct workspaces concurrently.
  //
  // This value must be a valid filename for the operating system on
  // which the remote output service and client are being executed. This
  // allows the remote output service to create one subdirectory per
  // project that needs to be built.
  //
  // By default, Bazel sets this value to the MD5 sum of the absolute
  // path of the workspace directory. This is generally sufficient,
  // though a more complex scheme may necessary in case the file system
  // namespace is virtualized.
  //
  // Starting a build finalizes any previous build with the same
  // workspace_id that has not been finalized yet.
  string workspace_id = 2;

  // The absolute path at which the remote output service exposes its
  // output paths, as seen from the perspective of the client.
  //
  // This value needs to be provided by the client, because file system
  // namespace virtualization may cause this directory to appear at a
  // location that differs from the one used by the service.
  //
  // The purpose of this field is to ensure that the remote output
  // service is capable of expanding symbolic links containing absolute
  // paths.
  string output_path = 3;

  // TODO(chiwang): fields for RBE authentication?
}

message InitialOutputPathContents {
  // Paths that have been modified or removed since the build finalized.
  //
  // If the remote output service freezes the contents of the output
  // path between builds, this field can be left empty.
  repeated string modified_paths = 1;
}

message StartBuildResponse {
  // If set, the contents of the output path are almost entirely
  // identical on the results of a previous build. This information may
  // be used by the client to prevent unnecessary scanning of the file
  // system.
  //
  // Servers can leave this field unset in case the contents of the
  // output path are empty, not based on a previous build, if no
  // tracking of this information is performed, or if the number of
  // changes made to the output path is too large to be expressed.
  InitialOutputPathContents initial_output_path_contents = 1;
}

message BatchCreateRequest {
  message File {
    string path = 1;
    int32 mode = 2;
    build.bazel.remote.execution.v2.Digest digest = 3;
  }

  message Directory {
    string path = 1;
    int32 mode = 2;
  }

  message Symlink {
    string path = 1;
    string target_path = 2;
  }

  // The identifier of the build. The remote output service uses this to
  // determine which output path needs to be modified.
  string build_id = 1;

  // Files that need to be downloaded from the Content Addressable
  // Storage.
  //
  // Any missing parent directories, including those in path_prefix, are
  // created as well. If any of the parents refer to a non-directory
  // file, they are replaced by an empty directory. If a file or
  // directory already exists at the provided path, it is replaced.
  //
  // This means that symbolic links are not followed when evaluating
  // path_prefix and OutputFile.path.
  repeated File files = 2;

  // Symbolic links that need to be created.
  //
  // Any missing parent directories, including those in path_prefix, are
  // created as well. If any of the parents refer to a non-directory
  // file, they are replaced by an empty directory. If a file or
  // directory already exists at the provided path, it is replaced.
  //
  // This means that symbolic links are not followed when evaluating
  // path_prefix and OutputSymlink.path.
  repeated Symlink symlinks = 3;

  // Directories that need to be downloaded from the Content Addressable
  // Storage.
  //
  // Any missing parent directories, including those in path_prefix, are
  // created as well. If any of the parents refer to a non-directory
  // file, they are replaced by an empty directory. Any file or
  // directory that already exists at the provided path is replaced.
  //
  // This means that symbolic links are not followed when evaluating
  // path_prefix and OutputDirectory.path.
  repeated Directory directories = 4;
}

message FinalizeBuildRequest {
  // The identifier of the build that should be finalized.
  string build_id = 1;

  // Whether the build completed successfully. The remote output service
  // may, for example, use this option to apply different retention
  // policies that take the outcome of the build into account.
  bool build_successful = 2;
}