// Companion proto that contains REv2 speicific types.

syntax = "proto3";

package bazel_output_service_rev2;

import "build/bazel/remote/execution/v2/remote_execution.proto";

option java_package = "com.google.devtools.build.lib.remote";
option java_outer_classname = "BazelOutputServiceREv2Proto";
option go_package = "bazeloutputservicerev2";

message StartBuildArgs {
  // The endpoint for the Content Addressable Storage.
  //
  // Bazel sets to this value to --remote_cache (or --remote_executor, in case
  // --remote_cache is not explicitly set).
  string remote_cache = 1;

  // The instance name that Bazel uses when communicating with the remote
  // execution system. The remote output service uses this value when loading
  // objects from the Content Addressable Storage.
  //
  // Bazel sets this value to --remote_instance_name.
  string instance_name = 2;

  // The digest function that Bazel uses when communicating with the remote
  // execution system. The remote output service uses this value to ensure
  // that FileStatus responses contain digests that were computed with right
  // digest function.
  //
  // Bazel sets this value to one of the digest functions in the REAPI sepc
  // according to --digest_function.
  build.bazel.remote.execution.v2.DigestFunction.Value digest_function = 3;
}

message FileArtifactLocator {
  build.bazel.remote.execution.v2.Digest digest = 1;
}

message TreeArtifactLocator {
  build.bazel.remote.execution.v2.Digest tree_digest = 1;
  build.bazel.remote.execution.v2.Digest root_directory_digest = 2;
}
